'''
Even Fibonnaci Numbers

Problem Description:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

count = 0

t1 = 0
t2 = 1

# use for loop for most efficient fib sequence generation
while t2 < 4000000:
    temp = t2
    t2 = t1+t2
    t1 = temp
    if t2 % 2 == 0:
        count += t2

print(count)
